[openai_api_key]
openai_api_key = "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"
